spring:
  profiles:
    active: dev

security.basic.enabled: false
management.security.enabled: false
security.ignored: /**

server.port: 9091
---

spring:
  profiles: dev
datasource:
  driver: org.h2.Driver
  url: jdbc:h2:mem:devopsdb
  username: sa
  password:

---

spring:
  profiles: prod



